### ISSUE TITLE
Some fixes across npm build --prod errors

### ISSUE THREAD

**Issue by SayChunKim** [ibonkonesa/barber-shop#1]
Style SCSS Change

From
`import '@mdi/css/materialdesignicons.css'`
To
`import '@mdi/font/css/materialdesignicons.css'`

And package.json update
```
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "@mdi/font": "^2.8.94",
    "axios": "^0.18.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "buefy": "^0.8.15", // buefy latest version is 0.8.15
    "core-js": "^3.6.4",
    "firebase": "^7.14.0",   
    "uuid": "^3.3.2",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vue2-datepicker": "^2.4.2",
    "vuex": "^3.0.1",
    "vuexfire": "^3.0.0-alpha.9"
  },
  "devDependencies": {
    "@vue/cli": "^4.3.1",
    "@vue/cli-service": "^4.3.1",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "^2.5.17"
  }
}
```
in function package.json

```
"engines": {
    "node": "8"
  }
```

Nice project btw

**Comment by ibonkonesa** [comment]
Thank you! I will update this soon

**Comment by ibonkonesa** [comment]
I appreciate your feedback. I have been reviewing this project and I noticed some issues:

- Current reservations wheren't shown, in fact the store was trying to get a non existent document.
- Modals behaviour was wrong. I cheked the booking flow in order to fix this. 
- Schedule color are the worst. 
- There was a mismatching in date times shown and how they are stored

I did this project when I was learning Vue. I'm sure now that this code is a shit, but I hope the idea was cool.
